from typing import Annotated, Literal
from operator import add

from pydantic import BaseModel, Field


class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(
        ...,
        description="List of messages to be processed."
    )
    
    
    user_ques: str = Field(
        ...,
        description="User Question is being asked by the user."
    )
    curated_ques: str = Field(
        ...,
        description="Curated user question."
    )

    prompt_query_context: str = Field(
        ...,
        description="A detailed prompt containing the SQL database context."
    )

    is_safe: Literal["Yes", "No"] = Field(
        ...,
        description="Indicates whether the generated SQL query is safe to execute."
    )

    generated_sql_query: str = Field(
        ...,
        description="The SQL query generated by the agent."
    )

    sql_query_execution_result: str = Field(
        ...,
        description="The result of executing the generated SQL query."
    )
    
    final_answer : str = Field(...,description ="The Final answer gernated by the agent based on sql.")


class JudgeSchema(BaseModel):
    answer : Literal["Yes","No"] = Field(..., description="Indicates whether the generated SQL query is safe to execute or not")
    comments : str = Field(..., description="Additional comments or feedback from the judge regarding the SQL query")
